### ISSUE TITLE
Header covers admin bar dropdowns

### ISSUE THREAD

**Issue by johnstonphilip** [brandid/course-maker-pro#15]
**Describe the bug**
The header of the theme covers the dropdown options from the WordPress admin bar. 

**To Reproduce**
1. Hover over the top admin bar while viewing the theme.
2. Hover over the "New" option.
3. Notice you cannot see all of the available options.

**Expected behavior**
The header does not cover the admin bars dropdown menus.

**Screenshots**
<img width="328" alt="Screen Shot 2020-06-12 at 1 13 19 PM" src="https://user-images.githubusercontent.com/7538525/84529025-bd64ac80-acae-11ea-83db-af8d522b04fc.png">

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser: Chrome
 - Version: 83.0.4103.61 (Official Build) (64-bit)

**Comment by alexmustin** [comment]
Thanks for posting this, @johnstonphilip ! 
We'll schedule this into our development pipeline.
