### ISSUE TITLE
PHP notice Undefined variable: total_lessons

### ISSUE THREAD

**Issue by dreamwhisper** [brandid/course-maker-pro#9]
**Describe the bug**

Undefined variable: total_lessons | 1 | +wp-content/themes/course-maker-pro/lifterlms/course/lesson-preview.php:56
-- | -- | --

**To Reproduce**
1. Install query monitor or use an alternate debugging method.
2. After importing the sample lesson, go to /lesson/what-are-your-core-values/
3. Note the Notice above

**Comment by alexmustin** [comment]
This file was copied from the LifterLMS plugin files, and is being used in the theme as a template override. I have not changed the code which is generating the error, so I've reached out to the LifterLMS developers for advice.
